spring:
  web:
    resources:
      static-locations:
        - file:D:/javawork/websocket/server-websocket/src/main/resources/static/upload/
  servlet:
    multipart:
      max-file-size: 10MB
  # ===========================
  # SpringDoc-OpenAPI 配置示例
  # ===========================
  springdoc:
    swagger-ui:
      # 自定义 Swagger 前端访问路径。
      # 例如访问 http://localhost:8000/swagger-ui
      # 会自动重定向到 Swagger 可视化页面。
      path: /doc.html
      # 对标签 (tags) 进行排序，alpha 表示按字母顺序排序。
      tags-sorter: alpha
      # 对接口 (operations) 进行排序，alpha 表示按字母顺序排序。
      operations-sorter: alpha
    api-docs:
      # Swagger/OpenAPI 的后端文档请求地址。
      # 通常用于前端 Swagger-UI 获取接口定义。
      path: /v3/api-docs
      # 是否启用接口文档功能。
      # 设置为 false 可在生产环境关闭接口文档。
      enabled: true
    group-configs:
      # -------- 分组配置开始 --------
      # 当项目接口较多或模块化较强时，
      # 可以通过分组来分别展示不同模块的接口文档。
      - group: 'default'              # 分组名称（默认组）
        paths-to-match: '/**'         # 匹配的接口路径（支持通配符）
        packages-to-scan: cn.wqk.serverwebsocket   # 要扫描的包路径，一般为启动类所在包
      # - group: 'admin-api'           # （示例）另一个分组，可按需启用
      #   paths-to-match: '/admin/**'  # 仅扫描 /admin 路径下的接口
      #   packages-to-scan: com.example.newtest.admin  # 扫描 admin 模块包
    mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # mysql数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/chat?useSSL=false&serverTimezone=UTC
    username: root
    password: yq040809
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis数据库配置
  data:
    redis:
      # redis数据库索引(默认为0)
      database: 0
      # redis服务器地址（默认为localhost）
      host: localhost
      # redis端口（默认为6379）
      port: 6379
      # redis访问密码（默认为空）
      password:
      # redis连接超时时间（单位毫秒）:不能设置为0，否则报无法连接
      timeout: 6000ms
      # redis高级客户端
      lettuce:
        pool:
          # 最大可用连接数（默认为8，负数表示无限）
          max-active: 8
          # 最大空闲连接数（默认为8，负数表示无限）
          max-idle: 8
          # 最小空闲连接数（默认为0，该值只有为正数才有用）
          min-idle: 0
          # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
          max-wait: -1
# mybatis配置
mybatis:
  # mapper.xml路径
  mapper-locations: classpath:mapper/**/*Mapper.xml
# 日志
logging:
  # 配置
  config: classpath:log4j2_dev.xml
  pattern:
    # 控制台输出颜色
    console: '%clr(%d{yyyyMMdd HH:mm:ss}){yellow} [%clr(%thread){red}] %-5level --- %clr(%logger){blue} | %msg%n'
# 端口
server:
  port: 8000
image:
  # 等一下看 用找个的地方
  mapping: /file/
  location: D:\javawork\websocket\server-websocket\src\main\resources\static\upload\


